const LOAD_TODOS = {
    REQUEST: 'LOAD_TODOS_REQUEST',
    SUCCESS: 'LOAD_TODOS_SUCCESS',
    FAIL: 'LOAD_TODOS_FAIL'
}

const ADD_TODO = {
    REQUEST: 'ADD_TODO_REQUEST',
    SUCCESS: 'ADD_TODO_SUCCESS',
    FAIL: 'ADD_TODO_FAIL'
}

const DELETE_TODO = {
    REQUEST: 'DELETE_TODO_REQUEST',
    SUCCESS: 'DELETE_TODO_SUCCESS',
    FAIL: 'DELETE_TODO_FAIL'
}

export {
    LOAD_TODOS,
    ADD_TODO,
    DELETE_TODO,
}